[package]
name = "tsp50cxx"
version = "0.1.0"
edition = "2021"

[dependencies]
arbitrary-int = "1.2.7"
bitflags = "2.6.0"
inline_colorization = "0.1.5"
terminal_size = "0.3.0"
unicode-width = "0.1.13"
